run:
  timeout: 5m
  issues-exit-code: 1
  tests: true
  modules-download-mode: readonly

# This is required for golangci-lint v2+
version: "2"

linters:
  enable:
    - govet
    - ineffassign
    - misspell
    - revive
    - staticcheck
    - unused
    - goconst
    - gocyclo
    - gosec
    - errcheck
    - lll
  settings:
    gocyclo:
      min-complexity: 15
    
    goconst:
      min-occurrences: 3
    
    govet:
      enable:
        - shadow
    
    misspell:
      locale: US
    
    lll:
      line-length: 120

    revive:
      rules:
        - name: exported
          arguments: [checkPrivateReceivers, sayRepetitiveInsteadOfStutters]

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
