run:
  timeout: 5m
  issues-exit-code: 1
  tests: true

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters-settings:
  gocyclo:
    min-complexity: 15
  
  goconst:
    min-occurrences: 3
  
  gofumpt:
    extra-rules: true
  
  govet:
    check-shadowing: true
  
  misspell:
    locale: US
  
  lll:
    line-length: 120

  revive:
    rules:
      - name: exported
        arguments: [checkPrivateReceivers, sayRepetitiveInsteadOfStutters]

linters:
  enable:
    - gofmt
    - gofumpt
    - goimports
    - govet
    - ineffassign
    - misspell
    - revive
    - staticcheck
    - unused
    - goconst
    - gocyclo
    - gosec
    - errcheck
    - lll
  disable:
    - typecheck

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - gosec
        - lll
