name: Bug Report
description: File a bug report to help us improve
title: "[BUG] "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible.

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: A clear and concise description of what the bug is.
      placeholder: Tell us what you see!
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: What should have happened?
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Run command '...'
        2. With parameters '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Please provide information about your environment
      value: |
        - OS: [e.g., Linux, macOS]
        - Architecture: [e.g., amd64, arm64]
        - Memory Calculator Version: [e.g., v1.0.0]
        - Container Runtime: [e.g., Docker, Podman, none]
        - Go Version (if building from source): [e.g., 1.24.5]
    validations:
      required: true

  - type: textarea
    id: command
    attributes:
      label: Command Used
      description: The exact command that caused the issue
      placeholder: "./memory-calculator --total-memory 2G --thread-count 250"

  - type: textarea
    id: output
    attributes:
      label: Actual Output
      description: The actual output you received
      render: shell

  - type: textarea
    id: logs
    attributes:
      label: Additional Context
      description: Add any other context about the problem here (logs, screenshots, etc.)

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      description: By submitting this issue, you agree to follow our Code of Conduct
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have provided all requested information
          required: true
